package cs134.miracosta.edu.energyhouse.model;

/**
 * ImpactItem.java - Represents an item that impacts the environment
 *
 * @author Dennis La
 * @version 1.0
 */
public class ImpactItem
{
    private long mId;
    private double mPoundsOfPaper;
    private double mPoundsOfMixedRecyclables;

    /**
     * Default constructor
     */
    public ImpactItem()
    {
        mId = -1;
        mPoundsOfPaper = 0.0;
        mPoundsOfMixedRecyclables = 0.0;
    }

    /**
     * Constructor that takes in poundsOfPaper and poundsOfMixedRecyclables
     *
     * @param poundsOfPaper pounds of paper
     * @param poundsOfMixedRecyclables pounds of mix recyclables
     */
    public ImpactItem(double poundsOfPaper, double poundsOfMixedRecyclables)
    {
        mId = -1;
        mPoundsOfPaper = poundsOfPaper;
        mPoundsOfMixedRecyclables = poundsOfMixedRecyclables;
    }

    /**
     * Constructor that takes in poundsOfPaper, poundsOfMixedRecyclables and id
     *
     * @param id the id of the item generated by the database
     * @param poundsOfPaper pounds of paper
     * @param poundsOfMixedRecyclables pounds of mix recyclables
     */
    public ImpactItem(long id, double poundsOfPaper, double poundsOfMixedRecyclables)
    {
        mId = id;
        mPoundsOfPaper = poundsOfPaper;
        mPoundsOfMixedRecyclables = poundsOfMixedRecyclables;
    }

    /**
     * Gets pounds of paper
     *
     * @return pounds of paper
     */
    public double getPoundsOfPaper() {
        return mPoundsOfPaper;
    }

    /**
     * Sets pounds of paper
     * @param poundsOfPaper pounds of paper
     */
    public void setPoundsOfPaper(double poundsOfPaper) {
        mPoundsOfPaper = poundsOfPaper;
    }

    /**
     * Gets pounds of mixed recyclables
     *
     * @return pounds of mixed recyclables
     */
    public double getPoundsOfMixedRecyclables() {
        return mPoundsOfMixedRecyclables;
    }

    /**
     * Sets pounds of mixed recyclables
     * @param poundsOfMixedRecyclables pounds of mixed recyclables
     */
    public void setPoundsOfMixedRecyclables(double poundsOfMixedRecyclables) {
        mPoundsOfMixedRecyclables = poundsOfMixedRecyclables;
    }

    /**
     * Gets id
     *
     * @return id
     */
    public long getId() {
        return mId;
    }

    /**
     * Sets id
     *
     * @param id the id
     */
    public void setId(long id) {
        mId = id;
    }

    /**
     * Calculate number of trees saved
     *
     * @return number of trees saved
     */
    public double calcNumTreesSaved()
    {
        return -0.049 + 0.14 * mPoundsOfPaper;
    }

    /**
     * Calculate number of gallons of oil saved
     *
     * @return number of gallons of oil saved
     */
    public double calcNumGallonsOfOilSaved()
    {
        double numGallons = 0;

        numGallons += -0.008 + 1.328 * mPoundsOfPaper;
        numGallons += 0.083 + 1.94 * mPoundsOfMixedRecyclables;

        return numGallons;
    }

    /**
     * Calculate number of hours of electricity saved
     *
     * @return number of hours of electricity saved
     */
    public double calcHoursOfElectricitySaved()
    {
        double numHours = 0;

        numHours += -1.75 + 13.91 * mPoundsOfPaper;
        numHours += 0.046 + 12.27 * mPoundsOfMixedRecyclables;

        return numHours;
    }

    /**
     * Calculate number of gallons of water saved
     *
     * @return number of gallons of water saved
     */
    public double calcNumGallonsOfWaterSaved()
    {
        return 0.2 + 41.6 * mPoundsOfPaper;
    }


}
