package cs134.miracosta.edu.energyhouse.model;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * RecycleLocation.java - Class to represent a recycling location/facility
 *
 * @author Dennis La
 * @version 1.0
 */
public class RecycleLocation implements Parcelable
{
    private long mId;
    private String mName;
    private String mAddress;
    private String mCity;
    private String mState;
    private String mZipCode;
    private String mPhone;
    private double mLatitude;
    private double mLongitude;

    /**
     * Full constructor for the location that takes in all the information. Id is generated by
     * the database
     *
     * @param id of location
     * @param name of location
     * @param address of location
     * @param city of location
     * @param state of location
     * @param zipCode of location
     * @param phone of location
     * @param latitude of location
     * @param longitude of location
     */
    public RecycleLocation(long id, String name, String address, String city, String state,
                           String zipCode, String phone, double latitude, double longitude)
    {
        mId = id;
        mName = name;
        mAddress = address;
        mCity = city;
        mState = state;
        mZipCode = zipCode;
        mPhone = phone;
        mLatitude = latitude;
        mLongitude = longitude;
    }

    /**
     * Constructor for the location that takes in all the information except id
     *
     * @param name of location
     * @param address of location
     * @param city of location
     * @param state of location
     * @param zipCode of location
     * @param phone of location
     * @param latitude of location
     * @param longitude of location
     */
    public RecycleLocation(String name, String address, String city, String state,
                           String zipCode, String phone, double latitude, double longitude)
    {
        this(-1, name, address, city, state, zipCode, phone, latitude, longitude);
    }

    /**
     * Makes a RecycleLocation from a parcel
     *
     * @param recyclingLocationParcel the parcel
     */
    protected RecycleLocation(Parcel recyclingLocationParcel) {
        mId = recyclingLocationParcel.readLong();
        mName = recyclingLocationParcel.readString();
        mAddress = recyclingLocationParcel.readString();
        mCity = recyclingLocationParcel.readString();
        mState = recyclingLocationParcel.readString();
        mZipCode = recyclingLocationParcel.readString();
        mPhone = recyclingLocationParcel.readString();
        mLatitude = recyclingLocationParcel.readDouble();
        mLongitude = recyclingLocationParcel.readDouble();
    }

    /**
     * Gets the id of location
     *
     * @return the id of location
     */
    public long getId() {
        return mId;
    }

    /**
     * Sets the id of location
     *
     * @param id of location
     */
    public void setId(long id) {
        mId = id;
    }

    /**
     * Gets the name of location
     *
     * @return the name of location
     */
    public String getName() {
        return mName;
    }

    /**
     * Sets the name of location
     *
     * @param name of location
     */
    public void setName(String name) {
        mName = name;
    }

    /**
     * Gets the address of location
     *
     * @return the address of location
     */
    public String getAddress() {
        return mAddress;
    }

    /**
     * Sets the address of location
     *
     * @param address of location
     */
    public void setAddress(String address) {
        mAddress = address;
    }

    /**
     * Gets the city of location
     *
     * @return the city of location
     */
    public String getCity() {
        return mCity;
    }

    /**
     * Sets the city of location
     *
     * @param city of location
     */
    public void setCity(String city) {
        mCity = city;
    }

    /**
     * Gets the state of location
     *
     * @return the state of location
     */
    public String getState() {
        return mState;
    }

    /**
     * Sets the state of location
     *
     * @param state of location
     */
    public void setState(String state) {
        mState = state;
    }

    /**
     * Gets the zip of location
     *
     * @return the zip of location
     */
    public String getZipCode() {
        return mZipCode;
    }

    /**
     * Sets the zipCode of location
     *
     * @param zipCode of location
     */
    public void setZipCode(String zipCode) {
        mZipCode = zipCode;
    }

    /**
     * Gets the phone of location
     *
     * @return the phone of location
     */
    public String getPhone() {
        return mPhone;
    }

    /**
     * Sets the phone of location
     *
     * @param phone of location
     */
    public void setPhone(String phone) {
        mPhone = phone;
    }

    /**
     * Gets the latitude of location
     *
     * @return the latitude of location
     */
    public double getLatitude() {
        return mLatitude;
    }

    /**
     * Sets the latitude of location
     *
     * @param latitude of location
     */
    public void setLatitude(double latitude) {
        mLatitude = latitude;
    }

    /**
     * Gets the longitude of location
     *
     * @return the longitude of location
     */
    public double getLongitude() {
        return mLongitude;
    }

    /**
     * Sets the longitude of location
     *
     * @param longitude of location
     */
    public void setLongitude(double longitude) {
        mLongitude = longitude;
    }

    /**
     * To string of the object
     *
     * @return string of info
     */
    @Override
    public String toString() {
        return "RecycleLocation{" +
                "Id=" + mId +
                ", Name='" + mName + '\'' +
                ", Address='" + mAddress + '\'' +
                ", City='" + mCity + '\'' +
                ", State='" + mState + '\'' +
                ", Zip Code='" + mZipCode + '\'' +
                ", Phone='" + mPhone + '\'' +
                ", Latitude=" + mLatitude +
                ", Longitude=" + mLongitude +
                '}';
    }

    /**
     * Gets string of some info about the object
     *
     * @return string of info
     */
    public String getInfo()
    {
        return mName + '\n' + mAddress + '\n' + mCity +
                '\n' + mState + '\n' + mZipCode +  + '\n' + mPhone;
    }

    /**
     * Stub
     *
     * @return 0
     */
    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * Writes object to a parcel
     *
     * @param parcel the parcel to write to
     * @param i
     */
    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeLong(mId);
        parcel.writeString(mName);
        parcel.writeString(mAddress);
        parcel.writeString(mCity);
        parcel.writeString(mState);
        parcel.writeString(mZipCode);
        parcel.writeString(mPhone);
        parcel.writeDouble(mLatitude);
        parcel.writeDouble(mLongitude);
    }

    /**
     * Anonymous inner class for create an array of RecycleLocation
     */
    public static final Creator<RecycleLocation> CREATOR = new Creator<RecycleLocation>() {

        /**
         * Creates RecycleLocation from parcel
         *
         * @param in the parcel
         * @return a new RecycleLocation
         */
        @Override
        public RecycleLocation createFromParcel(Parcel in) {
            return new RecycleLocation(in);
        }

        /**
         * Creates an array of RecycleLocation of length size
         *
         * @param size size of array
         * @return an array of RecycleLocation
         */
        @Override
        public RecycleLocation[] newArray(int size) {
            return new RecycleLocation[size];
        }
    };
}