package cs134.miracosta.edu.energyhouse.model;

import android.os.Parcel;
import android.os.Parcelable;
/**
 * SolarPanels.java - Class to fetch and handle information about solar panels
 *
 * @author JoshuaShor
 * @version 1.0
 */
public class SolarPanels implements Parcelable {

    private long mId;
    private String mName;
    private double mCosts;
    private double mWatts;
    private double mSqft;

    /**
     * Full constructor for the Solar Panels, ID generated by the database
     * @param id
     * @param name
     * @param costs
     * @param watts
     * @param sqft
     */
    public SolarPanels(long id, String name, double costs, double watts, double sqft) {
        mId = id;
        mName = name;
        mCosts = costs;
        mWatts = watts;
        mSqft = sqft;
    }

    /**
     * Instantiates a new Solar Panel information without unique ID.
     * @param name
     * @param costs
     * @param watts
     * @param sqft
     */
    public SolarPanels(String name, double costs, double watts, double sqft) {
        this(-1, name, costs, watts, sqft);
    }

    /**
     * Makes the information the Solar Panel class parcelable
     * @param solarPanelParcel
     */
    protected SolarPanels(Parcel solarPanelParcel) {

        mId = solarPanelParcel.readLong();
        mName = solarPanelParcel.readString();
        mCosts = solarPanelParcel.readDouble();
        mWatts = solarPanelParcel.readDouble();
        mSqft = solarPanelParcel.readDouble();
    }

    /**
     * Sets the unique id of the SolarPanels in database.
     * @param id
     */
    public void setId(long id) {
        mId = id;
    }

    /**
     *  Instantiates the name (or Type) of Solar Panel.
     * @param name
     */
    public void setName(String name) {
        mName = name;
    }


    /**
     * Instantiates the costs of the Solar Panel.
     * @param costs
     */
    public void setCosts(double costs) {
        mCosts = costs;
    }

    /**
     * Instantiates the wattage of the Solar Panel.
     * @param watts
     */
    public void setWatts(double watts) {
        mWatts = watts;
    }

    /**
     * Instantiates the square feet of the Solar Panel.
     * @param sqft
     */
    public void setSqft(double sqft) {
        mSqft = sqft;
    }

    /**
     * Gets the ID of solar panel
     * @return id of SolarPanel
     */
    public long getId() {
        return mId;
    }

    /**
     * Gets the name of solar panel
     * @return name of SolarPanel
     */
    public String getName() {
        return mName;
    }

    /**
     * Gets the cost of solar panel
     * @return cost of Solar Panel
     */
    public double getCosts() {
        return mCosts;
    }

    /**
     * Gets the wattage of solar panel
     * @return wattage of Solar Panel
     */
    public double getWatts() {
        return mWatts;
    }

    /**
     * Gets the square footag of solar panel
     * @return square footage of Solar Panel
     */
    public double getSqft() {
        return mSqft;
    }

    /**
     * toString method for the Solar Panel Class
     * @return a String of all the values
     */
    @Override
    public String toString() {
        return "SolarPanels{" +
                "mId=" + mId +
                ", mName='" + mName + '\'' +
                ", mCosts=" + mCosts +
                ", mWatts=" + mWatts +
                ", mSqft=" + mSqft +
                '}';
    }

    /**
     * Writes object to a parcel
     *
     * @param parcel the parcel to write to
     * @param i
     */
    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeLong(mId);
        parcel.writeString(mName);
        parcel.writeDouble(mCosts);
        parcel.writeDouble(mWatts);
        parcel.writeDouble(mSqft);
    }

    /**
     * stub
     * @return 0
     */
    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * Anonymous inner class to create an array of SolarPanels
     */
    public static final Creator<SolarPanels> CREATOR = new Creator<SolarPanels>() {

        /**
         * Creates SolarPanel from Parcel
         * @param in the parcel
         * @return a new SolarPanels
         */
        @Override
        public SolarPanels createFromParcel(Parcel in) {
            return new SolarPanels(in);
        }

        /**
         * Creates an array of SolarPanels of length size
         *
         * @param size of the array
         * @return an array of SolarPanels
         */

        @Override
        public SolarPanels[] newArray(int size) {
            return new SolarPanels[size];
        }
    };
}
