package cs134.miracosta.edu.energyhouse.model;

public class UsageTracker {

    long mId;
    String mDayStr;
    String mTimeStr;
    double mWattsUsed;

    /**
     * Empty Constructor so method is an easy call
     */
    public UsageTracker(){}

    /**
     * Full constructor for the UsageTracker, ID generated by the database
     * @param id
     * @param dayStr
     * @param timeStr
     * @param wattsUsed
     */
    public UsageTracker(long id, String dayStr, String timeStr, double wattsUsed) {
        mId = id;
        mDayStr = dayStr;
        mTimeStr = timeStr;
        mWattsUsed = wattsUsed;
    }

    /**
     * Instantiates a new Usage Tracked information without unique ID.
     * @param dayStr
     * @param timeStr
     * @param wattsUsed
     */
    public UsageTracker(String dayStr, String timeStr, double wattsUsed) {
        mId = -1;
        mDayStr = dayStr;
        mTimeStr = timeStr;
        mWattsUsed = wattsUsed;
    }

    /**
     * Sets the unique id of the Usage Tracked in database.
     * @param id
     */
    public void setId(long id) {
        mId = id;
    }

    /**
     * Sets the day of the Usage Tracked in database.
     * @param dayStr
     */
    public void setDayStr(String dayStr) {
        mDayStr = dayStr;
    }

    /**
     * Sets the time of the Usage Tracked in database.
     * @param timeStr
     */
    public void setTimeStr(String timeStr) {
        mTimeStr = timeStr;
    }

    /**
     * Sets the watts of the Usage Tracked in database.
     * @param wattsUsed
     */
    public void setWattsUsed(double wattsUsed) {
        mWattsUsed = wattsUsed;
    }

    /**
     * Gets the ID of Usage Tracked info
     * @return id
     */
    public long getId() {
        return mId;
    }

    /**
     * Gets the day of Usage Tracked info
     * @return day of year
     */
    public String getDayStr() {
        return mDayStr;
    }

    /**
     * Gets the time of Usage Tracked info
     * @return Time of Day
     */
    public String getTimeStr() {
        return mTimeStr;
    }

    /**
     * Gets the watts of Usage Tracked info
     * @return watts used
     */
    public double getWattsUsed() {
        return mWattsUsed;
    }

    /**
     * toString method for the UsageTracker Class
     * @return a String of all the values
     */
    @Override
    public String toString() {
        return "UsageTracker{" +
                "mId=" + mId +
                ", mDayStr='" + mDayStr + '\'' +
                ", mTimeStr='" + mTimeStr + '\'' +
                ", mWattsUsed=" + mWattsUsed +
                '}';
    }
}
